package com.example.prama.security;

import org.springframework.context.annotation.Lazy;
import org.springframework.messaging.Message;
import org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler;
import org.springframework.messaging.simp.broker.SubscriptionRegistry;
import org.springframework.messaging.simp.SimpMessageHeaderAccessor;
import org.springframework.messaging.simp.SimpMessageType;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.util.MultiValueMap;
import org.springframework.stereotype.Service;
import lombok.extern.slf4j.Slf4j;
import java.util.List;

@Service
@Slf4j
public class RealTimeSubscriptionEnforcer {

    private final SimpleBrokerMessageHandler brokerMessageHandler;

    // 🛡️ Constructor injection with @Lazy proxy to prevent circular dependency
    public RealTimeSubscriptionEnforcer(@Lazy SimpleBrokerMessageHandler brokerMessageHandler) {
        this.brokerMessageHandler = brokerMessageHandler;
    }

    /**
     * Surgical Excision: Forcibly unregisters a target session from a specific group topic.
     * Invoked node-wide instantly upon receiving the MEMBER_EVICTED cluster signal.
     */
    public void exciseGroupSubscription(String sessionId, String groupId) {
        String targetDestination = "/topic/group." + groupId;
        SubscriptionRegistry registry = brokerMessageHandler.getSubscriptionRegistry();
        
        try {
            // 1. Construct a probe message to query the registry for matching destinations
            Message<?> probeMessage = MessageBuilder.withPayload(new byte[0])
                .setHeader(SimpMessageHeaderAccessor.DESTINATION_HEADER, targetDestination)
                .build();
            
            // Returns an active map (SessionId -> SubscriptionIds)
            MultiValueMap<String, String> activeSubscriptions = registry.findSubscriptions(probeMessage);
            
            // 2. Isolate the subscriptionIds generated by this specific evicted user session
            List<String> targetSubscriptionIds = activeSubscriptions.get(sessionId);
            
            if (targetSubscriptionIds != null && !targetSubscriptionIds.isEmpty()) {
                // Loop to catch any multi-tab duplicate subscriptions to the same topic
                for (String subId : targetSubscriptionIds) {
                    
                    // 3. Build a valid, simulated UNSUBSCRIBE message context expected by Spring
                    SimpMessageHeaderAccessor accessor = SimpMessageHeaderAccessor.create(SimpMessageType.UNSUBSCRIBE);
                    accessor.setSessionId(sessionId);
                    accessor.setSubscriptionId(subId);
                    
                    Message<byte[]> unsubscribeMessage = MessageBuilder.createMessage(
                        new byte[0], 
                        accessor.getMessageHeaders()
                    );
                    
                    // 4. Execute surgical, compile-safe excision
                    registry.unregisterSubscription(unsubscribeMessage);
                }
                
                log.info("🛡️ [Broker Excision]: Successfully severed session {} from destination {}", 
                    sessionId, targetDestination);
            } else {
                log.info("ℹ️ [Broker Excision]: No active subscription found for session {} on destination {}", 
                    sessionId, targetDestination);
            }
        } catch (Exception e) {
            log.error("❌ [Broker Excision Error]: Failed to excise subscription for session {}", 
                sessionId, e);
        }
    }
}
